/* tslint:disable */
/* eslint-disable */
/**
 * GreenPath API
 * GreenPath 서비스의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApiResponseCourseExploreResponse {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: CourseExploreResponse;
}
export interface ApiResponseCourseRecordResultResponse {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: CourseRecordResultResponse;
}
export interface ApiResponseCourseResponse {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: CourseResponse;
}
export interface ApiResponseListCourseResponse {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: Array<CourseResponse>;
}
export interface ApiResponseLong {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: number;
}
export interface ApiResponseMyPageResponse {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: MyPageResponse;
}
export interface ApiResponseString {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: string;
}
export interface ApiResponseTokenResponse {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: TokenResponse;
}
export interface ApiResponseVoid {
    'timestamp'?: string;
    'status'?: number;
    'message'?: string;
    'data'?: object;
}
export interface BadgeInfo {
    'code'?: string;
    'name'?: string;
}
export interface CO2 {
    'amount'?: number;
    'treeEquivalent'?: number;
}
export interface CourseCompleteRequest {
    'courseId'?: number;
    'startTime'?: string;
    'endTime'?: string;
    'visitedSpotIds'?: Array<number>;
    'distance'?: number;
}
export interface CourseExploreResponse {
    'id'?: number;
    'code'?: string;
    'courseId'?: number;
    'courseCode'?: string;
    'name'?: string;
    'summary'?: string;
    'description'?: string;
    'latitude'?: number;
    'longitude'?: number;
    'imageUrl'?: string;
}
export interface CourseRecordResultResponse {
    'recordId'?: number;
    'courseTitle'?: string;
    'summary'?: Summary;
    'co2'?: CO2;
    'reward'?: Reward;
    'badge'?: BadgeInfo;
}
export interface CourseRequest {
    'mood'?: CourseRequestMoodEnum;
    'duration'?: CourseRequestDurationEnum;
    'level'?: CourseRequestLevelEnum;
    'location'?: CourseRequestLocationEnum;
    'latitude'?: number;
    'longitude'?: number;
    'preferenceText'?: string;
}

export const CourseRequestMoodEnum = {
    Quiet: 'QUIET',
    Photo: 'PHOTO',
    History: 'HISTORY',
    Hip: 'HIP',
} as const;

export type CourseRequestMoodEnum = typeof CourseRequestMoodEnum[keyof typeof CourseRequestMoodEnum];
export const CourseRequestDurationEnum = {
    OneHour: 'ONE_HOUR',
    TwoHours: 'TWO_HOURS',
    HalfDay: 'HALF_DAY',
} as const;

export type CourseRequestDurationEnum = typeof CourseRequestDurationEnum[keyof typeof CourseRequestDurationEnum];
export const CourseRequestLevelEnum = {
    Easy: 'EASY',
    Medium: 'MEDIUM',
    Any: 'ANY',
} as const;

export type CourseRequestLevelEnum = typeof CourseRequestLevelEnum[keyof typeof CourseRequestLevelEnum];
export const CourseRequestLocationEnum = {
    Nearby: 'NEARBY',
    Any: 'ANY',
} as const;

export type CourseRequestLocationEnum = typeof CourseRequestLocationEnum[keyof typeof CourseRequestLocationEnum];

export interface CourseResponse {
    'courseId'?: number;
    'code'?: string;
    'title'?: string;
    'description'?: string;
    'summary'?: CourseSummary;
    'stops'?: Array<CourseStop>;
    'polyline'?: string;
    'createdAt'?: string;
}
export interface CourseStop {
    'code'?: string;
    'order'?: number;
    'name'?: string;
    'summary'?: string;
    'description'?: string;
    'stayMinutes'?: number;
    'latitude'?: number;
    'longitude'?: number;
    'imageUrl'?: string;
}
export interface CourseSummary {
    'distanceKm'?: number;
    'durationMinutes'?: number;
    'difficulty'?: CourseSummaryDifficultyEnum;
    'carbonReductionKg'?: number;
}

export const CourseSummaryDifficultyEnum = {
    Easy: 'EASY',
    Medium: 'MEDIUM',
    Any: 'ANY',
} as const;

export type CourseSummaryDifficultyEnum = typeof CourseSummaryDifficultyEnum[keyof typeof CourseSummaryDifficultyEnum];

/**
 * 로그인 요청 데이터
 */
export interface LoginRequest {
    /**
     * 이메일 주소
     */
    'email': string;
    'password': string;
}
export interface MyPageResponse {
    'user'?: UserInfo;
    'stats'?: Stats;
    'badges'?: Array<BadgeInfo>;
    'recentRecords'?: Array<RecentRecord>;
}
export interface RecentRecord {
    'recordId'?: number;
    'title'?: string;
    'date'?: string;
    'point'?: number;
}
export interface ReissueRequest {
    'refreshToken': string;
}
export interface Reward {
    'basePoint'?: number;
    'bonusPoint'?: number;
    'totalPoint'?: number;
}
/**
 * 회원가입 요청 데이터
 */
export interface SignUpRequest {
    /**
     * 이메일 주소
     */
    'email': string;
    /**
     * 비밀번호 (8~20자 영문, 숫자, 특수문자 포함)
     */
    'password': string;
    /**
     * 사용자 이름
     */
    'name': string;
}
export interface Stats {
    'totalCo2'?: number;
    'totalDistance'?: number;
    'visitedCount'?: number;
    'totalPoint'?: number;
}
export interface Summary {
    'distance'?: number;
    'duration'?: number;
    'visitedCount'?: number;
}
export interface TokenResponse {
    'accessToken'?: string;
    'refreshToken'?: string;
    'tokenType'?: string;
    'accessTokenExpiresIn'?: number;
}
export interface UserInfo {
    'name'?: string;
    'level'?: number;
    'levelName'?: string;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 회원가입 전 이메일 중복 여부를 확인합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkEmail: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('checkEmail', 'email', email)
            const localVarPath = `/api/auth/check-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 이메일과 비밀번호를 통해 로그인하고 인증 토큰을 발급받습니다.
         * @summary 로그인
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/api/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자의 Refresh Token을 DB에서 삭제합니다.
         * @summary 로그아웃
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Refresh Token을 제출하여 새로운 Access/Refresh 토큰을 재발급받습니다.
         * @summary 토큰 재발급
         * @param {ReissueRequest} reissueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reissue: async (reissueRequest: ReissueRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reissueRequest' is not null or undefined
            assertParamExists('reissue', 'reissueRequest', reissueRequest)
            const localVarPath = `/api/auth/reissue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reissueRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기본 정보(이메일, 비밀번호, 이름)로 회원가입을 진행합니다.
         * @summary 회원 가입
         * @param {SignUpRequest} signUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUp: async (signUpRequest: SignUpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signUpRequest' is not null or undefined
            assertParamExists('signUp', 'signUpRequest', signUpRequest)
            const localVarPath = `/api/auth/sign-up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 회원가입 전 이메일 중복 여부를 확인합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkEmail(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkEmail(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.checkEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 이메일과 비밀번호를 통해 로그인하고 인증 토큰을 발급받습니다.
         * @summary 로그인
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자의 Refresh Token을 DB에서 삭제합니다.
         * @summary 로그아웃
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Refresh Token을 제출하여 새로운 Access/Refresh 토큰을 재발급받습니다.
         * @summary 토큰 재발급
         * @param {ReissueRequest} reissueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reissue(reissueRequest: ReissueRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reissue(reissueRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.reissue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기본 정보(이메일, 비밀번호, 이름)로 회원가입을 진행합니다.
         * @summary 회원 가입
         * @param {SignUpRequest} signUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUp(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUp(signUpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signUp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 회원가입 전 이메일 중복 여부를 확인합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkEmail(email: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.checkEmail(email, options).then((request) => request(axios, basePath));
        },
        /**
         * 이메일과 비밀번호를 통해 로그인하고 인증 토큰을 발급받습니다.
         * @summary 로그인
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseTokenResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자의 Refresh Token을 DB에서 삭제합니다.
         * @summary 로그아웃
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
        /**
         * Refresh Token을 제출하여 새로운 Access/Refresh 토큰을 재발급받습니다.
         * @summary 토큰 재발급
         * @param {ReissueRequest} reissueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reissue(reissueRequest: ReissueRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseTokenResponse> {
            return localVarFp.reissue(reissueRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 기본 정보(이메일, 비밀번호, 이름)로 회원가입을 진행합니다.
         * @summary 회원 가입
         * @param {SignUpRequest} signUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUp(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseLong> {
            return localVarFp.signUp(signUpRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 회원가입 전 이메일 중복 여부를 확인합니다.
     * @summary 이메일 중복 확인
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public checkEmail(email: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).checkEmail(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 이메일과 비밀번호를 통해 로그인하고 인증 토큰을 발급받습니다.
     * @summary 로그인
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자의 Refresh Token을 DB에서 삭제합니다.
     * @summary 로그아웃
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public logout(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Refresh Token을 제출하여 새로운 Access/Refresh 토큰을 재발급받습니다.
     * @summary 토큰 재발급
     * @param {ReissueRequest} reissueRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public reissue(reissueRequest: ReissueRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).reissue(reissueRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기본 정보(이메일, 비밀번호, 이름)로 회원가입을 진행합니다.
     * @summary 회원 가입
     * @param {SignUpRequest} signUpRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public signUp(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signUp(signUpRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CourseApi - axios parameter creator
 */
export const CourseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 탐방 종료 시 주행 거리 및 방문 정보를 기록하고 포인트를 획득합니다.
         * @summary 탐방 완료 처리
         * @param {CourseCompleteRequest} courseCompleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeExploration: async (courseCompleteRequest: CourseCompleteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseCompleteRequest' is not null or undefined
            assertParamExists('completeExploration', 'courseCompleteRequest', courseCompleteRequest)
            const localVarPath = `/api/v1/courses/complete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(courseCompleteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 선택한 코스에 대한 정보를 반환합니다.
         * @summary 코스 상세 정보 조회
         * @param {number} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourseDetail: async (courseId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('getCourseDetail', 'courseId', courseId)
            const localVarPath = `/api/v1/courses/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 탐방 중인 코스의 특정 순서 경유지 정보를 가져옵니다.
         * @summary 경유지 상세 정보 조회
         * @param {number} courseId 
         * @param {number} stopOrder 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourseStopInfo: async (courseId: number, stopOrder: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('getCourseStopInfo', 'courseId', courseId)
            // verify required parameter 'stopOrder' is not null or undefined
            assertParamExists('getCourseStopInfo', 'stopOrder', stopOrder)
            const localVarPath = `/api/v1/courses/{courseId}/stops/{stopOrder}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)))
                .replace(`{${"stopOrder"}}`, encodeURIComponent(String(stopOrder)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기록 ID를 통해 과거 탐방 결과를 다시 조회합니다.
         * @summary 탐방 기록 상세 조회
         * @param {number} recordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExploreRecordResult: async (recordId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recordId' is not null or undefined
            assertParamExists('getExploreRecordResult', 'recordId', recordId)
            const localVarPath = `/api/v1/courses/records/{recordId}`
                .replace(`{${"recordId"}}`, encodeURIComponent(String(recordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 분위기, 소요 시간, 난이도 등 유저 설정에 맞는 AI 추천 코스를 제안합니다.
         * @summary 맞춤 코스 추천
         * @param {CourseRequest} [courseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommend: async (courseRequest?: CourseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/courses/recommend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(courseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CourseApi - functional programming interface
 */
export const CourseApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CourseApiAxiosParamCreator(configuration)
    return {
        /**
         * 탐방 종료 시 주행 거리 및 방문 정보를 기록하고 포인트를 획득합니다.
         * @summary 탐방 완료 처리
         * @param {CourseCompleteRequest} courseCompleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async completeExploration(courseCompleteRequest: CourseCompleteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCourseRecordResultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.completeExploration(courseCompleteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseApi.completeExploration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 선택한 코스에 대한 정보를 반환합니다.
         * @summary 코스 상세 정보 조회
         * @param {number} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCourseDetail(courseId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCourseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCourseDetail(courseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseApi.getCourseDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 탐방 중인 코스의 특정 순서 경유지 정보를 가져옵니다.
         * @summary 경유지 상세 정보 조회
         * @param {number} courseId 
         * @param {number} stopOrder 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCourseStopInfo(courseId: number, stopOrder: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCourseExploreResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCourseStopInfo(courseId, stopOrder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseApi.getCourseStopInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기록 ID를 통해 과거 탐방 결과를 다시 조회합니다.
         * @summary 탐방 기록 상세 조회
         * @param {number} recordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExploreRecordResult(recordId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCourseRecordResultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExploreRecordResult(recordId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseApi.getExploreRecordResult']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 분위기, 소요 시간, 난이도 등 유저 설정에 맞는 AI 추천 코스를 제안합니다.
         * @summary 맞춤 코스 추천
         * @param {CourseRequest} [courseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommend(courseRequest?: CourseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListCourseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommend(courseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseApi.recommend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CourseApi - factory interface
 */
export const CourseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CourseApiFp(configuration)
    return {
        /**
         * 탐방 종료 시 주행 거리 및 방문 정보를 기록하고 포인트를 획득합니다.
         * @summary 탐방 완료 처리
         * @param {CourseCompleteRequest} courseCompleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeExploration(courseCompleteRequest: CourseCompleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCourseRecordResultResponse> {
            return localVarFp.completeExploration(courseCompleteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 선택한 코스에 대한 정보를 반환합니다.
         * @summary 코스 상세 정보 조회
         * @param {number} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourseDetail(courseId: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCourseResponse> {
            return localVarFp.getCourseDetail(courseId, options).then((request) => request(axios, basePath));
        },
        /**
         * 탐방 중인 코스의 특정 순서 경유지 정보를 가져옵니다.
         * @summary 경유지 상세 정보 조회
         * @param {number} courseId 
         * @param {number} stopOrder 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourseStopInfo(courseId: number, stopOrder: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCourseExploreResponse> {
            return localVarFp.getCourseStopInfo(courseId, stopOrder, options).then((request) => request(axios, basePath));
        },
        /**
         * 기록 ID를 통해 과거 탐방 결과를 다시 조회합니다.
         * @summary 탐방 기록 상세 조회
         * @param {number} recordId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExploreRecordResult(recordId: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCourseRecordResultResponse> {
            return localVarFp.getExploreRecordResult(recordId, options).then((request) => request(axios, basePath));
        },
        /**
         * 분위기, 소요 시간, 난이도 등 유저 설정에 맞는 AI 추천 코스를 제안합니다.
         * @summary 맞춤 코스 추천
         * @param {CourseRequest} [courseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommend(courseRequest?: CourseRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListCourseResponse> {
            return localVarFp.recommend(courseRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CourseApi - object-oriented interface
 */
export class CourseApi extends BaseAPI {
    /**
     * 탐방 종료 시 주행 거리 및 방문 정보를 기록하고 포인트를 획득합니다.
     * @summary 탐방 완료 처리
     * @param {CourseCompleteRequest} courseCompleteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public completeExploration(courseCompleteRequest: CourseCompleteRequest, options?: RawAxiosRequestConfig) {
        return CourseApiFp(this.configuration).completeExploration(courseCompleteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 선택한 코스에 대한 정보를 반환합니다.
     * @summary 코스 상세 정보 조회
     * @param {number} courseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCourseDetail(courseId: number, options?: RawAxiosRequestConfig) {
        return CourseApiFp(this.configuration).getCourseDetail(courseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 탐방 중인 코스의 특정 순서 경유지 정보를 가져옵니다.
     * @summary 경유지 상세 정보 조회
     * @param {number} courseId 
     * @param {number} stopOrder 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCourseStopInfo(courseId: number, stopOrder: number, options?: RawAxiosRequestConfig) {
        return CourseApiFp(this.configuration).getCourseStopInfo(courseId, stopOrder, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기록 ID를 통해 과거 탐방 결과를 다시 조회합니다.
     * @summary 탐방 기록 상세 조회
     * @param {number} recordId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getExploreRecordResult(recordId: number, options?: RawAxiosRequestConfig) {
        return CourseApiFp(this.configuration).getExploreRecordResult(recordId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 분위기, 소요 시간, 난이도 등 유저 설정에 맞는 AI 추천 코스를 제안합니다.
     * @summary 맞춤 코스 추천
     * @param {CourseRequest} [courseRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recommend(courseRequest?: CourseRequest, options?: RawAxiosRequestConfig) {
        return CourseApiFp(this.configuration).recommend(courseRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MemberApi - axios parameter creator
 */
export const MemberApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 사용자의 레벨, 누적 통계, 획득 뱃지 및 최근 기록을 조회합니다.
         * @summary 마이페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyPage: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/members/me/mypage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MemberApi - functional programming interface
 */
export const MemberApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MemberApiAxiosParamCreator(configuration)
    return {
        /**
         * 사용자의 레벨, 누적 통계, 획득 뱃지 및 최근 기록을 조회합니다.
         * @summary 마이페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyPage(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseMyPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyPage(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberApi.getMyPage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MemberApi - factory interface
 */
export const MemberApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MemberApiFp(configuration)
    return {
        /**
         * 사용자의 레벨, 누적 통계, 획득 뱃지 및 최근 기록을 조회합니다.
         * @summary 마이페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyPage(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseMyPageResponse> {
            return localVarFp.getMyPage(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MemberApi - object-oriented interface
 */
export class MemberApi extends BaseAPI {
    /**
     * 사용자의 레벨, 누적 통계, 획득 뱃지 및 최근 기록을 조회합니다.
     * @summary 마이페이지 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyPage(options?: RawAxiosRequestConfig) {
        return MemberApiFp(this.configuration).getMyPage(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MemberPreferenceApi - axios parameter creator
 */
export const MemberPreferenceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 분위기, 소급시간, 난이도 및 좌표를 저장합니다.
         * @summary 사용자 취향 설정/업데이트
         * @param {CourseRequest} courseRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        savePreference: async (courseRequest: CourseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseRequest' is not null or undefined
            assertParamExists('savePreference', 'courseRequest', courseRequest)
            const localVarPath = `/api/v1/members/preferences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwtAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(courseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MemberPreferenceApi - functional programming interface
 */
export const MemberPreferenceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MemberPreferenceApiAxiosParamCreator(configuration)
    return {
        /**
         * 분위기, 소급시간, 난이도 및 좌표를 저장합니다.
         * @summary 사용자 취향 설정/업데이트
         * @param {CourseRequest} courseRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async savePreference(courseRequest: CourseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.savePreference(courseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemberPreferenceApi.savePreference']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MemberPreferenceApi - factory interface
 */
export const MemberPreferenceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MemberPreferenceApiFp(configuration)
    return {
        /**
         * 분위기, 소급시간, 난이도 및 좌표를 저장합니다.
         * @summary 사용자 취향 설정/업데이트
         * @param {CourseRequest} courseRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        savePreference(courseRequest: CourseRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseString> {
            return localVarFp.savePreference(courseRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MemberPreferenceApi - object-oriented interface
 */
export class MemberPreferenceApi extends BaseAPI {
    /**
     * 분위기, 소급시간, 난이도 및 좌표를 저장합니다.
     * @summary 사용자 취향 설정/업데이트
     * @param {CourseRequest} courseRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public savePreference(courseRequest: CourseRequest, options?: RawAxiosRequestConfig) {
        return MemberPreferenceApiFp(this.configuration).savePreference(courseRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



